version: '3.4'

services:
  storekeeper:
    image: storekeeper
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: Production
    ports:
      - 5001:5001
