version: '3.4'

services:
  storekeeper:
    image: storekeeper
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "main.js"]
